#!/usr/bin/env bash

# Kanagawa Minimal Theme for Tmux
# Palette: sumiInk1=#1f1f28, sumiInk3=#363646, waveBlue2=#2d4f67, fujiWhite=#dcd7ba, oniViolet=#957fb8, springBlue=#7e9cd8

set -g mode-style "fg=#7e9cd8,bg=#363646"

set -g message-style "fg=#dcd7ba,bg=#2a2a37"
set -g message-command-style "fg=#dcd7ba,bg=#2a2a37"

set -g pane-border-style "fg=#2a2a37"
set -g pane-active-border-style "fg=#7e9cd8"

set -g status "on"
set -g status-justify "left"
set -g status-position "bottom"

# 기본 상태바 배경
set -g status-style "fg=#727169,bg=#1f1f28"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

# 왼쪽: 세션 아이콘 + 이름
set -g status-left "#[fg=#957fb8,bold]  #S #[fg=#727169,nobold] "

# 오른쪽: 날짜 + 시간
set -g status-right "#[fg=#727169] %m-%d  %H:%M "

setw -g window-status-activity-style "underscore,fg=#dcd7ba,bg=#1f1f28"
setw -g window-status-separator "  "
setw -g window-status-style "NONE,fg=#727169,bg=#1f1f28"

# 일반 윈도우
setw -g window-status-format "#I #W"

# 활성 윈도우
setw -g window-status-current-format "#[fg=#dcd7ba,bold]#I #W#[fg=#957fb8]*"
